"""pocetna migracija

Revision ID: eb0b02c01baa
Revises: 
Create Date: 2026-09-12 14:21:46.603504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0b02c01baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lijecnici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('specijalizacija', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacijenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=30), nullable=False),
    sa.Column('prezime', sa.String(length=30), nullable=False),
    sa.Column('telefon', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usluge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('cijena', sa.Float(), nullable=False),
    sa.Column('trajanje', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termini',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.String(length=20), nullable=False),
    sa.Column('vrijeme', sa.String(length=10), nullable=False),
    sa.Column('pacijent_id', sa.Integer(), nullable=False),
    sa.Column('lijecnik_id', sa.Integer(), nullable=False),
    sa.Column('usluga_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lijecnik_id'], ['lijecnici.id'], ),
    sa.ForeignKeyConstraint(['pacijent_id'], ['pacijenti.id'], ),
    sa.ForeignKeyConstraint(['usluga_id'], ['usluge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('termini')
    op.drop_table('usluge')
    op.drop_table('pacijenti')
    op.drop_table('lijecnici')
    # ### end Alembic commands ###
